'use client'

import { useParams } from 'next/navigation'
import { AdminHeader } from '@/components/ui/AdminHeader'
import { SectionCard } from '@/components/features/SectionCard'
import { InfoRow } from '@/components/features/InfoRow'
import { StatusBadge } from '@/components/ui/StatusBadge'
import ReportSharing from '../components/ReportSharing'

export default function ReportDetailPage() {
  const params = useParams<{ id: string }>()
  const id = params?.id ?? 'RPT-101'

  return (
    <div className="space-y-6">
      <AdminHeader
        title="Report Detail"
        description={`Report: ${id}`}
        breadcrumbs={[{ label: 'Reports', href: '/reports' }, { label: id }]}
        actions={<StatusBadge variant="success" label="Completed" />}
      />
      <SectionCard title="Report Information">
        <div>
          <InfoRow label="Name" value="August Revenue Report" />
          <InfoRow label="Type" value="Revenue" />
          <InfoRow label="Format" value="PDF" />
          <InfoRow label="Generated by" value="Admin - J. Kimani" />
          <InfoRow label="Generated" value="2026-08-01 06:30" />
          <InfoRow label="Size" value="1.2 MB" />
        </div>
      </SectionCard>
      <ReportSharing />
    </div>
  )
}